version: '3.8'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: discord-bot-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: discord-music-bot
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  # Optional: MongoDB Express for database management
  mongo-express:
    image: mongo-express:latest
    container_name: discord-bot-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/discord-music-bot
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data:
