version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: discord-bot-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: discord-music-bot
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - discord-bot-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Lavalink Audio Server
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    container_name: discord-bot-lavalink
    restart: unless-stopped
    environment:
      SERVER_PORT: 2333
      LAVALINK_SERVER_PASSWORD: your_lavalink_password_here
      JAVA_OPTS: -Xmx512m
    ports:
      - "2333:2333"
    volumes:
      - ../lavalink/application.yml:/opt/Lavalink/application.yml:ro
      - ../lavalink/plugins:/opt/Lavalink/plugins:ro
    networks:
      - discord-bot-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2333/version"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    depends_on:
      - mongodb

  # Discord Bot
  discord-bot:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: discord-bot
    restart: unless-stopped
    environment:
      # Discord Configuration
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      GUILD_ID: ${GUILD_ID:-}
      BOT_PREFIX: ${BOT_PREFIX:-!}
      BOT_OWNERS: ${BOT_OWNERS:-}
      
      # Database Configuration
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/discord-music-bot?authSource=admin
      
      # Lavalink Configuration
      LAVALINK_HOST: lavalink
      LAVALINK_PORT: 2333
      LAVALINK_PASSWORD: your_lavalink_password_here
      LAVALINK_SECURE: false
      
      # Spotify Configuration (optional)
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID:-}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET:-}
      
      # OpenAI Configuration (optional)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      
      # Bot Settings
      DEFAULT_VOLUME: ${DEFAULT_VOLUME:-50}
      MAX_QUEUE_SIZE: ${MAX_QUEUE_SIZE:-100}
      PREMIUM_MAX_QUEUE_SIZE: ${PREMIUM_MAX_QUEUE_SIZE:-500}
      COMMAND_COOLDOWN: ${COMMAND_COOLDOWN:-3000}
      PREMIUM_COMMAND_COOLDOWN: ${PREMIUM_COMMAND_COOLDOWN:-1000}
      AUTO_DEPLOY_COMMANDS: ${AUTO_DEPLOY_COMMANDS:-true}
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-info}
      
      # Node Environment
      NODE_ENV: production
    volumes:
      - bot_logs:/app/logs
      - bot_transcripts:/app/transcripts
    networks:
      - discord-bot-network
    depends_on:
      mongodb:
        condition: service_healthy
      lavalink:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mongodb_data:
    driver: local
  bot_logs:
    driver: local
  bot_transcripts:
    driver: local

networks:
  discord-bot-network:
    driver: bridge
