name: Test Docker Build

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'src/**'
      - 'Docker/**'
      - 'package*.json'
      - '.github/workflows/**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/Dockerfile
          platforms: linux/amd64
          push: false
          tags: discord-bot:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test container startup
        run: |
          # Create a test environment file
          cat > test.env << EOF
          DISCORD_TOKEN=test_token_placeholder
          CLIENT_ID=123456789
          MONGODB_URI=mongodb://localhost:27017/test
          LAVALINK_HOST=localhost
          LAVALINK_PORT=2333
          LAVALINK_PASSWORD=test
          NODE_ENV=test
          EOF
          
          # Test that the container can start (it will fail due to invalid token, but that's expected)
          timeout 30s docker run --rm --env-file test.env discord-bot:test || true
          
          echo "✅ Docker build test completed successfully"

  security-scan:
    runs-on: ubuntu-latest
    needs: test-build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for scanning
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/Dockerfile
          load: true
          tags: discord-bot:scan
          cache-from: type=gha

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'discord-bot:scan'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
